hard_hand_strategy = \
    [
        [  # 2        3         4        5        6       7         8       9       10       A
            ['stand', 'stand', 'stand', 'stand', 'stand', 'stand', 'stand', 'stand', 'stand', 'stand'],
            ['stand', 'stand', 'stand', 'stand', 'stand', 'stand', 'stand', 'stand', 'stand', 'stand'],
            ['stand', 'stand', 'stand', 'stand', 'stand', 'stand', 'stand', 'stand', 'stand', 'stand'],
            ['stand', 'stand', 'stand', 'stand', 'stand', 'stand', 'stand', 'stand', 'stand', 'stand'],
            ['stand', 'stand', 'stand', 'stand', 'stand',  'hit',   'hit',   'surrender',   'surrender',   'surrender'],
            ['stand', 'stand', 'stand', 'stand', 'stand',  'hit',   'hit',   'hit',   'surrender',   'hit'],
            ['stand', 'stand', 'stand', 'stand', 'stand',  'hit',   'hit',   'hit',   'hit',   'hit'],
            ['stand', 'stand', 'stand', 'stand', 'stand',  'hit',   'hit',   'hit',   'hit',   'hit'],       # -3
            ['hit',    'hit',  'stand', 'stand', 'stand',  'hit',   'hit',   'hit',   'hit',   'hit'],
            ['double', 'double', 'double', 'double', 'double', 'double', 'double', 'double', 'double', 'double'],
            ['double', 'double', 'double', 'double', 'double', 'double', 'double', 'double', 'hit', 'hit'],
            ['hit',    'double', 'double', 'double', 'double', 'hit',   'hit',   'hit',   'hit',   'hit'],
            ['hit',    'hit',   'hit',   'hit',   'hit',   'hit',   'hit',   'hit',   'hit',   'hit'],
            ['hit',    'hit',   'hit',   'hit',   'hit',   'hit',   'hit',   'hit',   'hit',   'hit'],
            ['hit',    'hit',   'hit',   'hit',   'hit',   'hit',   'hit',   'hit',   'hit',   'hit'],
            ['hit',    'hit',   'hit',   'hit',   'hit',   'hit',   'hit',   'hit',   'hit',   'hit'],
            ['hit',    'hit',   'hit',   'hit',   'hit',   'hit',   'hit',   'hit',   'hit',   'hit']],
        [  # 2        3         4        5        6       7         8       9       10       A
            ['stand', 'stand', 'stand', 'stand', 'stand', 'stand', 'stand', 'stand', 'stand', 'stand'],
            ['stand', 'stand', 'stand', 'stand', 'stand', 'stand', 'stand', 'stand', 'stand', 'stand'],
            ['stand', 'stand', 'stand', 'stand', 'stand', 'stand', 'stand', 'stand', 'stand', 'stand'],
            ['stand', 'stand', 'stand', 'stand', 'stand', 'stand', 'stand', 'stand', 'stand', 'stand'],
            ['stand', 'stand', 'stand', 'stand', 'stand',  'hit',   'hit',   'surrender',   'surrender',   'surrender'],
            ['stand', 'stand', 'stand', 'stand', 'stand',  'hit',   'hit',   'hit',   'surrender',   'hit'],
            ['stand', 'stand', 'stand', 'stand', 'stand',  'hit',   'hit',   'hit',   'hit',   'hit'],
            ['stand', 'stand', 'stand', 'stand', 'stand',  'hit',   'hit',   'hit',   'hit',   'hit'],       # -2
            ['hit',    'hit',  'stand', 'stand', 'stand',  'hit',   'hit',   'hit',   'hit',   'hit'],
            ['double', 'double', 'double', 'double', 'double', 'double', 'double', 'double', 'double', 'double'],
            ['double', 'double', 'double', 'double', 'double', 'double', 'double', 'double', 'hit', 'hit'],
            ['hit',    'double', 'double', 'double', 'double', 'hit',   'hit',   'hit',   'hit',   'hit'],
            ['hit',    'hit',   'hit',   'hit',   'hit',   'hit',   'hit',   'hit',   'hit',   'hit'],
            ['hit',    'hit',   'hit',   'hit',   'hit',   'hit',   'hit',   'hit',   'hit',   'hit'],
            ['hit',    'hit',   'hit',   'hit',   'hit',   'hit',   'hit',   'hit',   'hit',   'hit'],
            ['hit',    'hit',   'hit',   'hit',   'hit',   'hit',   'hit',   'hit',   'hit',   'hit'],
            ['hit',    'hit',   'hit',   'hit',   'hit',   'hit',   'hit',   'hit',   'hit',   'hit']],
        [  # 2        3         4        5        6       7         8       9       10       A
            ['stand', 'stand', 'stand', 'stand', 'stand', 'stand', 'stand', 'stand', 'stand', 'stand'],
            ['stand', 'stand', 'stand', 'stand', 'stand', 'stand', 'stand', 'stand', 'stand', 'stand'],
            ['stand', 'stand', 'stand', 'stand', 'stand', 'stand', 'stand', 'stand', 'stand', 'stand'],
            ['stand', 'stand', 'stand', 'stand', 'stand', 'stand', 'stand', 'stand', 'stand', 'stand'],
            ['stand', 'stand', 'stand', 'stand', 'stand',  'hit',   'hit',   'surrender',   'surrender',   'surrender'],
            ['stand', 'stand', 'stand', 'stand', 'stand',  'hit',   'hit',   'hit',   'surrender',   'hit'],
            ['stand', 'stand', 'stand', 'stand', 'stand',  'hit',   'hit',   'hit',   'hit',   'hit'],
            ['stand', 'stand', 'stand', 'stand', 'stand',  'hit',   'hit',   'hit',   'hit',   'hit'],       # -1
            ['hit',    'hit',  'stand', 'stand', 'stand',  'hit',   'hit',   'hit',   'hit',   'hit'],
            ['double', 'double', 'double', 'double', 'double', 'double', 'double', 'double', 'double', 'double'],
            ['double', 'double', 'double', 'double', 'double', 'double', 'double', 'double', 'hit', 'hit'],
            ['hit',    'double', 'double', 'double', 'double', 'hit',   'hit',   'hit',   'hit',   'hit'],
            ['hit',    'hit',   'hit',   'hit',   'hit',   'hit',   'hit',   'hit',   'hit',   'hit'],
            ['hit',    'hit',   'hit',   'hit',   'hit',   'hit',   'hit',   'hit',   'hit',   'hit'],
            ['hit',    'hit',   'hit',   'hit',   'hit',   'hit',   'hit',   'hit',   'hit',   'hit'],
            ['hit',    'hit',   'hit',   'hit',   'hit',   'hit',   'hit',   'hit',   'hit',   'hit'],
            ['hit',    'hit',   'hit',   'hit',   'hit',   'hit',   'hit',   'hit',   'hit',   'hit']],
        [  # 2        3         4        5        6       7         8       9       10       A
            ['stand', 'stand', 'stand', 'stand', 'stand', 'stand', 'stand', 'stand', 'stand', 'stand'],
            ['stand', 'stand', 'stand', 'stand', 'stand', 'stand', 'stand', 'stand', 'stand', 'stand'],
            ['stand', 'stand', 'stand', 'stand', 'stand', 'stand', 'stand', 'stand', 'stand', 'stand'],
            ['stand', 'stand', 'stand', 'stand', 'stand', 'stand', 'stand', 'stand', 'stand', 'stand'],
            ['stand', 'stand', 'stand', 'stand', 'stand',  'hit',   'hit',   'surrender',   'surrender',   'surrender'],
            ['stand', 'stand', 'stand', 'stand', 'stand',  'hit',   'hit',   'hit',   'surrender',   'hit'],
            ['stand', 'stand', 'stand', 'stand', 'stand',  'hit',   'hit',   'hit',   'hit',   'hit'],
            ['stand', 'stand', 'stand', 'stand', 'stand',  'hit',   'hit',   'hit',   'hit',   'hit'],       # 0
            ['hit',    'hit',  'stand', 'stand', 'stand',  'hit',   'hit',   'hit',   'hit',   'hit'],
            ['double', 'double', 'double', 'double', 'double', 'double', 'double', 'double', 'double', 'double'],
            ['double', 'double', 'double', 'double', 'double', 'double', 'double', 'double', 'hit', 'hit'],
            ['hit',    'double', 'double', 'double', 'double', 'hit',   'hit',   'hit',   'hit',   'hit'],
            ['hit',    'hit',   'hit',   'hit',   'hit',   'hit',   'hit',   'hit',   'hit',   'hit'],
            ['hit',    'hit',   'hit',   'hit',   'hit',   'hit',   'hit',   'hit',   'hit',   'hit'],
            ['hit',    'hit',   'hit',   'hit',   'hit',   'hit',   'hit',   'hit',   'hit',   'hit'],
            ['hit',    'hit',   'hit',   'hit',   'hit',   'hit',   'hit',   'hit',   'hit',   'hit'],
            ['hit',    'hit',   'hit',   'hit',   'hit',   'hit',   'hit',   'hit',   'hit',   'hit']],
        [  # 2        3         4        5        6       7         8       9       10       A
            ['stand', 'stand', 'stand', 'stand', 'stand', 'stand', 'stand', 'stand', 'stand', 'stand'],
            ['stand', 'stand', 'stand', 'stand', 'stand', 'stand', 'stand', 'stand', 'stand', 'stand'],
            ['stand', 'stand', 'stand', 'stand', 'stand', 'stand', 'stand', 'stand', 'stand', 'stand'],
            ['stand', 'stand', 'stand', 'stand', 'stand', 'stand', 'stand', 'stand', 'stand', 'stand'],
            ['stand', 'stand', 'stand', 'stand', 'stand',  'hit',   'hit',   'surrender',   'stand',   'surrender'],
            ['stand', 'stand', 'stand', 'stand', 'stand',  'hit',   'hit',   'hit',   'surrender',   'hit'],
            ['stand', 'stand', 'stand', 'stand', 'stand',  'hit',   'hit',   'hit',   'hit',   'hit'],
            ['stand', 'stand', 'stand', 'stand', 'stand',  'hit',   'hit',   'hit',   'hit',   'hit'],       # 1
            ['hit',    'hit',  'stand', 'stand', 'stand',  'hit',   'hit',   'hit',   'hit',   'hit'],
            ['double', 'double', 'double', 'double', 'double', 'double', 'double', 'double', 'double', 'double'],
            ['double', 'double', 'double', 'double', 'double', 'double', 'double', 'double', 'hit', 'hit'],
            ['hit',    'double', 'double', 'double', 'double', 'hit',   'hit',   'hit',   'hit',   'hit'],
            ['hit',    'hit',   'hit',   'hit',   'hit',   'hit',   'hit',   'hit',   'hit',   'hit'],
            ['hit',    'hit',   'hit',   'hit',   'hit',   'hit',   'hit',   'hit',   'hit',   'hit'],
            ['hit',    'hit',   'hit',   'hit',   'hit',   'hit',   'hit',   'hit',   'hit',   'hit'],
            ['hit',    'hit',   'hit',   'hit',   'hit',   'hit',   'hit',   'hit',   'hit',   'hit'],
            ['hit',    'hit',   'hit',   'hit',   'hit',   'hit',   'hit',   'hit',   'hit',   'hit']],
        [  # 2        3         4        5        6       7         8       9       10       A
            ['stand', 'stand', 'stand', 'stand', 'stand', 'stand', 'stand', 'stand', 'stand', 'stand'],
            ['stand', 'stand', 'stand', 'stand', 'stand', 'stand', 'stand', 'stand', 'stand', 'stand'],
            ['stand', 'stand', 'stand', 'stand', 'stand', 'stand', 'stand', 'stand', 'stand', 'stand'],
            ['stand', 'stand', 'stand', 'stand', 'stand', 'stand', 'stand', 'stand', 'stand', 'stand'],
            ['stand', 'stand', 'stand', 'stand', 'stand',  'hit',   'hit',   'surrender',   'stand',   'surrender'],
            ['stand', 'stand', 'stand', 'stand', 'stand',  'hit',   'hit',   'hit',   'surrender',   'hit'],
            ['stand', 'stand', 'stand', 'stand', 'stand',  'hit',   'hit',   'hit',   'hit',   'hit'],
            ['stand', 'stand', 'stand', 'stand', 'stand',  'hit',   'hit',   'hit',   'hit',   'hit'],       # 2
            ['hit',    'hit',  'stand', 'stand', 'stand',  'hit',   'hit',   'hit',   'hit',   'hit'],
            ['double', 'double', 'double', 'double', 'double', 'double', 'double', 'double', 'double', 'double'],
            ['double', 'double', 'double', 'double', 'double', 'double', 'double', 'double', 'hit', 'hit'],
            ['hit',    'double', 'double', 'double', 'double', 'hit',   'hit',   'hit',   'hit',   'hit'],
            ['hit',    'hit',   'hit',   'hit',   'hit',   'hit',   'hit',   'hit',   'hit',   'hit'],
            ['hit',    'hit',   'hit',   'hit',   'hit',   'hit',   'hit',   'hit',   'hit',   'hit'],
            ['hit',    'hit',   'hit',   'hit',   'hit',   'hit',   'hit',   'hit',   'hit',   'hit'],
            ['hit',    'hit',   'hit',   'hit',   'hit',   'hit',   'hit',   'hit',   'hit',   'hit'],
            ['hit',    'hit',   'hit',   'hit',   'hit',   'hit',   'hit',   'hit',   'hit',   'hit']],
        [  # 2        3         4        5        6       7         8       9       10       A
            ['stand', 'stand', 'stand', 'stand', 'stand', 'stand', 'stand', 'stand', 'stand', 'stand'],
            ['stand', 'stand', 'stand', 'stand', 'stand', 'stand', 'stand', 'stand', 'stand', 'stand'],
            ['stand', 'stand', 'stand', 'stand', 'stand', 'stand', 'stand', 'stand', 'stand', 'stand'],
            ['stand', 'stand', 'stand', 'stand', 'stand', 'stand', 'stand', 'stand', 'stand', 'stand'],
            ['stand', 'stand', 'stand', 'stand', 'stand',  'hit',   'hit',   'surrender',   'stand',   'surrender'],
            ['stand', 'stand', 'stand', 'stand', 'stand',  'hit',   'hit',   'hit',   'surrender',   'hit'],
            ['stand', 'stand', 'stand', 'stand', 'stand',  'hit',   'hit',   'hit',   'hit',   'hit'],
            ['stand', 'stand', 'stand', 'stand', 'stand',  'hit',   'hit',   'hit',   'hit',   'hit'],       # 3
            ['hit',    'hit',  'stand', 'stand', 'stand',  'hit',   'hit',   'hit',   'hit',   'hit'],
            ['double', 'double', 'double', 'double', 'double', 'double', 'double', 'double', 'double', 'double'],
            ['double', 'double', 'double', 'double', 'double', 'double', 'double', 'double', 'hit', 'hit'],
            ['hit',    'double', 'double', 'double', 'double', 'hit',   'hit',   'hit',   'hit',   'hit'],
            ['hit',    'hit',   'hit',   'hit',   'hit',   'hit',   'hit',   'hit',   'hit',   'hit'],
            ['hit',    'hit',   'hit',   'hit',   'hit',   'hit',   'hit',   'hit',   'hit',   'hit'],
            ['hit',    'hit',   'hit',   'hit',   'hit',   'hit',   'hit',   'hit',   'hit',   'hit'],
            ['hit',    'hit',   'hit',   'hit',   'hit',   'hit',   'hit',   'hit',   'hit',   'hit'],
            ['hit',    'hit',   'hit',   'hit',   'hit',   'hit',   'hit',   'hit',   'hit',   'hit']]]